
name: pt_len_ahmadfathanhanif
services:
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=db;user=root;password=;database=${DB_NAME}
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - db
    networks:
      - pt_len

  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - pt_len
    # Add healthcheck to ensure MySQL is ready before API starts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pt_len:
    driver: bridge